CREATE TABLE NOTICE (	
    "NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(50), 
	"NOTICE_WRITER" VARCHAR2(15), 
	"NOTICE_CONTENT" VARCHAR2(2000), 
	"NOTICE_DATE" DATE DEFAULT SYSDATE, 
	"NOTICE_READCOUNT" NUMBER DEFAULT 0, 
    CONSTRAINT PK_NOTICE_NO PRIMARY KEY(NOTICE_NO),
    CONSTRAINT FK_NOTICE_WRITER FOREIGN KEY(NOTICE_WRITER) REFERENCES MEMBER_INFO(mem_id) ON DELETE SET NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '게시글번호';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '게시글제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_WRITER" IS '게시글작성자 아이디';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '게시글내용';
COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '게시글올린날짜';
COMMENT ON COLUMN "NOTICE"."NOTICE_READCOUNT" IS '조회수';

CREATE SEQUENCE SEQ_NOTICE_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

insert into semi.NOTICE(NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'admin공지사항 입니다 - 1','admin','반갑습니다',to_date('18/01/11','RR/MM/DD'),0);
insert into semi.NOTICE(NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 1','abcd','반갑습니다',to_date('18/01/11','RR/MM/DD'),0);
insert into semi.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT)values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 2','abcd','반갑습니다',to_date('18/02/10','RR/MM/DD'),0);
insert into semi.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT)values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 3','bcde','반갑습니다',to_date('18/02/12','RR/MM/DD'),0);
insert into semi.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT)values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 4','cdef','반갑습니다',to_date('18/02/13','RR/MM/DD'),0);
insert into semi.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT)values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 5','defg','반갑습니다',to_date('18/02/14','RR/MM/DD'),0);
insert into semi.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT)values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 6','efgh','반갑습니다',to_date('18/02/15','RR/MM/DD'),0);
insert into semi.NOTICE(NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,NOTICE_DATE,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'공지사항 입니다 - 7','fghi','반갑습니다',to_date('18/02/16','RR/MM/DD'),0);