create table SHOP(
SHOP_CODE		NUMBER          NOT NULL PRIMARY KEY,
SHOP_NAME		VARCHAR	(20)	NOT NULL,
SHOP_ADDR		VARCHAR	(50)    NOT NULL,
SHOP_PHONE		VARCHAR	(13)	NOT NULL,
SHOP_EMP_NUM		NUMBER		NOT NULL,
SHOP_BIKE_NUM		NUMBER		NOT NULL
);
insert into shop values(SEQ_SHOP_NO.NEXTVAL, '매직빈' ,'서울시강남구','01012345678' ,3,10);
insert into shop values(SEQ_SHOP_NO.NEXTVAL, 'BIKEE' ,'서울시강남구','01012345678' ,5,15);

COMMENT ON COLUMN "SHOP"."SHOP_CODE" IS '대여소코드';
COMMENT ON COLUMN "SHOP"."SHOP_NAME" IS '대여소이름';
COMMENT ON COLUMN "SHOP"."SHOP_ADDR" IS '대여소주소';
COMMENT ON COLUMN "SHOP"."SHOP_PHONE" IS '대여소전화번호';
COMMENT ON COLUMN "SHOP"."SHOP_EMP_NUM" IS '대여소직원수';
COMMENT ON COLUMN "SHOP"."SHOP_BIKE_NUM" IS '자전거갯수';

CREATE SEQUENCE SEQ_shop_NO
START WITH 1000
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;